#!/bin/bash
@Library('jenkinslib') _

def build = new org.devops.build()
String buildType = "${env.buildType}"
String buildShell = "${env.buildShell}"

//Pipeline
pipeline {
    agent { node {  label "master"   //指定运行节点的标签或者名称
                customWorkspace "${workspace}"   //指定运行工作目录（可选）
            }
    }

    stages {
        //下载代码
        stage("build"){ //阶段名称
            steps{  //步骤
                 script{ //填写运行代码
                        build.Build(buildType,buildShell)
                  }
            }
        }

    }

    //构建后操作
    post {
        always {
            script{
                println("always")
            }
        }

        success {
            script{
                currentBuild.description = "\n 构建成功!" 
            }
        }

        failure {
            script{
                currentBuild.description = "\n 构建失败!" 
            }
        }

        aborted {
            script{
                currentBuild.description = "\n 构建取消!" 
            }
        }
    }
}
