#!/bin/bash
@Library('jenkinslib') _

def build = new org.devops.build()
def deploy = new org.devops.deploy()

String buildType = "${env.buildType}"
String buildShell = "${env.buildShell}"
String deployHosts = "${env.deployHosts}"


//Pipeline
pipeline {
    agent { node {  label "master" 
            }
    }

    stages {
        //下载代码
        stage("build"){ 
            steps{
                 script{
                        build.Build(buildType,buildShell)
                        deploy.SaltDeploy("${deployHosts}","test.ping")
                        deploy.AnsibleDeploy("${deployHosts}","-m ping")
                  }
            }
        }

    }

    //构建后操作
    post {
        always {
            script{
                println("always")
            }
        }

        success {
            script{
                currentBuild.description = "\n 构建成功!" 
            }
        }

        failure {
            script{
                currentBuild.description = "\n 构建失败!" 
            }
        }

        aborted {
            script{
                currentBuild.description = "\n 构建取消!" 
            }
        }
    }
}
